version: '3'
services:

  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mi5
    volumes: 
      - db:/var/lib/mysql
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000
    depends_on:
      - mysql

volumes:
  db: