<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerADV3qhL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerADV3qhL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerADV3qhL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerADV3qhL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerADV3qhL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ADV3qhL',
    'container.build_id' => '219f960b',
    'container.build_time' => 1611149308,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerADV3qhL');
