<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGJ16xrJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGJ16xrJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGJ16xrJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGJ16xrJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGJ16xrJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GJ16xrJ',
    'container.build_id' => '5ed8b57b',
    'container.build_time' => 1611052484,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGJ16xrJ');
